# gradle
java_version=17
use_mixin=true

# minecraft
minecraft_version=1.18.2
parchmentmc_version=1.18.2:2022.11.06

# mod
archives_base_name=fishnostuck
maven_group=com.stevekung.fishnostuck
mod_version=1.0.2
enabled_platforms=fabric,forge

# fabric
fabric_loader_version=0.15.11

# forge
forge_version=40.2.17