apply from: "https://raw.githubusercontent.com/SteveKunG/GradleScripts/main/architectury/common.gradle"

dependencies {
    implementation("com.moulberry:mixinconstraints:${mixin_constraints_version}")
}

loom {
    mixin {
        useLegacyMixinAp = true
    }
}

tasks.shadowJar {
    zip64 = true
}